### ISSUE TITLE
Unable to iterate over get_paged generator when using parameters

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/rac_api_client#1]
**Describe the bug**
When iterating over the results of `get_paged` when using parameters, it fails immediately:

```
>>> for thing in my_client.get_paged('/objects', params={"online": True}):
...     thing
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bonniegordon/workspace/rac_api_client/rac_api_client/client.py", line 48, in get_paged
    while len(current_page["results"]):
TypeError: string indices must be integers
```

If `get_paged` is run without iterating over it, a generator object is successfully returned. However, when trying to iterate over _that_, the same failure as above happens.

I tried without parameters, and it worked successfully.

**To Reproduce**
1. Use the `get_page` method with parameters
2. Iterate over the resulting generator

**Expected behavior**
I expect to iterate over the things in the generator object.

**Additional context**
I tried to run the code `get_paged` line by line to reproduce the failure at `len(current_page["results"])` and could not reproduce the error.

It's possible my parameter syntax was off but I based it on what's in the readme.

**Comment by helrond** [comment]
This is related to how booleans are handled in JSON versus Python dictionaries. A request for `https://api.rockarch.org/objects?online=True` (which is what is being made in this case) returns a 500 while a request for `https://api.rockarch.org/objects?online=true` (lowercase t) does not.

The question is where to handle this inconsistency; in the client or in the API. I'm kind of inclined to do it in the client because it's specifically the Python dict to JSON conversion that's the issue here. 

Thoughts?

**Comment by bonniegee** [comment]
Thanks! I'd agree that handling this in the client makes the most sense.
